# 4. src/ableton_template_generator/config/default_settings.yml
application:
  name: "Ableton Template Generator"
  version: "1.0.0"
  
paths:
  templates: "templates"
  patterns: "templates/patterns"
  output: "output"
  
defaults:
  time_signature:
    numerator: 4
    denominator: 4
  
  colors:
    drums: "YELLOW"
    bass: "BLUE"
    harmony: "GREEN"
    lead: "RED"
    fx: "PURPLE"
    vocals: "ORANGE"
  
  track_types:
    drums: "BOTH"
    bass: "MIDI"
    synths: "MIDI"
    audio: "AUDIO"
  
  layers:
    default: 1
    max: 3